name: app_2i2i
description: 2i2i - the uber of talking

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  flutter_lints:
  universal_html: ^2.0.8
  sentry_flutter: ^6.3.0
  walletconnect_dart: ^0.0.7
  algorand_dart: ^1.0.1
  flutter_webrtc: ^0.8.3
  just_audio: ^0.9.20
  # just_audio_libwinmedia: ^0.0.4 # needed for Windows
  flutter_riverpod: ^1.0.3
  cloud_functions: ^3.2.9

  flutter_secure_storage: ^5.0.2
#  flutterfire_ui: ^0.3.4
  http: ^0.13.4
  url_launcher: ^6.0.20
  uni_links: ^0.5.1
  expansion_tile_card: ^2.0.0
  qr_flutter: ^4.0.0
  flutter_styled_toast: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^5.0.0+1
#  percent_indicator: ^4.0.0
  flutter_animator: ^3.2.1
  animate_countdown_text: ^1.1.3
  share_plus: ^3.1.0
  image_picker: ^0.8.4+10
  cloud_firestore: ^3.1.10
#  image_picker: ^0.8.4+9
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3
#  shimmer: ^2.0.0
  go_router: ^3.0.3
  intl: ^0.17.0
  # firebase_app_check: ^0.0.6+5 # add once works with firestore / needs iOS/Android setup
  cached_network_image: ^3.2.0

  firebase_messaging: ^11.2.8
  firebase_app_check: ^0.0.6+7
  firebase_auth: ^3.3.9


  device_info_plus: ^3.2.2
  rich_text_controller: ^1.4.0
  awesome_notifications: ^0.6.21
  permission_handler: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/2x/
    - assets/3x/
    - assets/icons/
    - assets/logo.png
    - assets/2i2i_letter.png
    - assets/video_call.mp3
    - assets/stopwatch.png
    - ios/Podfile
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia_Pro_ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Sofia_Pro_Light.otf
          weight: 300
        - asset: assets/fonts/Sofia_Pro_Regular.otf
          weight: 400
        - asset: assets/fonts/Sofia_Pro_Medium.otf
          weight: 500
        - asset: assets/fonts/Sofia_Pro_Semi_Bold.otf
          weight: 600
        - asset: assets/fonts/Sofia_Pro_Bold.otf
          weight: 700

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
