import '../../../infrastructure/commons/keys.dart';

class ar {
  Map data() {
    return {
      Keys.aboutYou: 'حولك',
      Keys.aboutYouDesc: 'من فضلك املأ هذه',
      Keys.faq: 'التعليمات',
      Keys.automatic: "تلقائي",
      Keys.shareQr: "شارك نفسك",
      Keys.error: 'خطأ',
      Keys.errorWhileAddBid: "خطأ أثناء إضافة عرض التسعير ، جرب حسابًا آخر أو قلل المدة القصوى أو قلل السرعة",
      Keys.less: 'أقل',
      Keys.importance: 'أهمية',
      Keys.chrony: "Chrony",
      Keys.highRoller: 'الأسطوانة عالية',
      Keys.theme: 'سمة',
      Keys.light: 'خفيفة',
      Keys.dark: 'داكن',
      Keys.auto: 'آلي',
      Keys.forever: 'إلى الأبد',
      Keys.minSpeed: "الحد الأدنى للدعم",
      Keys.maxDuration: "أقصى مدة",
      Keys.estWaitTime: 'Est. وقت الانتظار هو ',
      Keys.numberHint: "أدخل رقمًا حقيقيًا مثل 12",
      Keys.numberZeroHint: "0",
      Keys.algoPerSec: "ALGO/s",
      Keys.ALGO: "ALGO",
      Keys.hh: 'ح ح',
      Keys.mm: 'مم',
      Keys.ss: 's',
      Keys.invalid: 'غير صالح',
      Keys.join: 'انضم',
      Keys.favorites: "المفضلة",
      Keys.wallet: 'محفظة نقود',
      Keys.blockList: "الضيوف المحظورون",
      Keys.favList: "قائمة المفضلة",
      Keys.fav: "المفضلة",
      Keys.scanQr: "مسح QR",
      Keys.about: 'عن',
      Keys.aboutPageUrl: "https://about.2i2i.app",
      Keys.scanInWalletConnect: "استخدام WalletConnect \ n (على سبيل المثال Algorand Wallet)",
      Keys.appName: "2i2i",
      Keys.ok: 'موافق',
      Keys.talk: 'يتحدث',
      Keys.cancel: 'يلغي',
      Keys.ratings: "التقييمات",
      Keys.close: 'قريب',
      Keys.copyMessage: 'نسخ إلى الحافظة',
      Keys.userBusyMessage: "المستخدم غير متصل أو مشغول ..",
      Keys.logout: 'تسجيل خروج',
      Keys.noRatingsFound: "لم يتم العثور على تقييمات",
      Keys.logoutAreYouSure: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      Keys.logoutFailed: "فشل تسجيل الخروج",
      Keys.signIn: 'تسجيل الدخول',
      Keys.signInWithEmailPassword: "تسجيل الدخول باستخدام البريد الإلكتروني وكلمة المرور",
      Keys.goAnonymous: "الذهاب مجهول",
      Keys.or: 'أو',
      Keys.signInFailed: 'فشل تسجيل الدخول',
      Keys.somethingWantWrong: "شيء ما يريد خطأ",
      Keys.homePage: 'الصفحة الرئيسية',
      Keys.home: 'بحث',
      Keys.account: 'الملف الشخصي',
      Keys.doneIHaveCopied: "تم ونسخ",
      Keys.profile: 'يستضيف',
      Keys.settings: 'إعدادات',
      Keys.searchUserHint: "البحث عن مضيف",
      Keys.search: 'بحث',
      Keys.myAccount: 'حسابي',
      Keys.bidsIn: "العطاءات",
      Keys.bidsInPage: "العطاءات في الصفحة",
      Keys.topAppBarTitle: "2i2i",
      Keys.newCardTitle: 'بطاقة جديدة',
      Keys.createABid: "انضم إلى المضيف",
      Keys.speed: 'يدعم',
      Keys.bidAmount: 'قيمة المزايدة',
      Keys.note: "ملاحظة (اختياري)",
      Keys.bidNote: "قل شيئًا رائعًا",
      Keys.yourBioHint: "أحب أن # أتحدث و # أطبخ \ n أستطيع # التدريس",
      Keys.yourNameHint: "اسمي الرائع",
      Keys.writeYourBio: "اكتب سيرتك الذاتية",
      Keys.writeYourName: 'اكتب اسمك',
      Keys.bioExample: "مثال: لنتحدث عن # الطهي أو # كرة السلة",
      Keys.save: 'يحفظ',
      Keys.required: 'مطلوب',
      Keys.enterValidData: "الرجاء إدخال بيانات صحيحة",
      Keys.setUpAccount: 'من أنت؟',
      Keys.userSettings: "إعدادات المضيف",
      Keys.userName: 'اسم المستخدم',
      Keys.name: 'اسم المستخدم',
      Keys.bio: "اهتماماتك (استخدم علامات التصنيف)",
      Keys.addAccount: 'إنشاء حساب',
      Keys.walletAccount: "حساب المحفظة",
      Keys.walletAccountMsg: "أريد توصيل محفظة طرف ثالث",
      Keys.recoverPassphrase: "استرداد مع عبارة المرور",
      Keys.recoverPassPhaseMsg: "أعرف 25 كلمة سرية",
      Keys.addLocalAccount: "إضافة حساب محلي",
      Keys.addLocalAccountMsg: "إنشاء حساب محلي على هذا الجهاز",
      Keys.swipeAndChangeAccount: "مرر لتغيير الحساب",
      Keys.insufficientBalance: "رصيد غير كاف",
      Keys.addBid: 'انضم',
      Keys.next: "نسخ",
      Keys.report: 'نقل',
      Keys.block: 'منع',
      Keys.unBlock: 'رفع الحظر',
      Keys.seeMore: 'شاهد المزيد',
      Keys.more: 'أكثر',
      Keys.appRatingTitle: "هل أعجبك هذا الاجتماع؟",
      Keys.appRatingMessage: 'أي ردود فعل؟',
      Keys.appRatingSubmitButton: 'إرسال',
      Keys.selectNetworkMode: "حدد وضع الشبكة:",
      Keys.themeMode: 'نظام الألوان:',
      Keys.myProfile: 'ملفي',
      Keys.bidIn: "المزايدة في",
      Keys.bidOut: 'منتظر',
      Keys.noBidFound: "لم يتم العثور على عروض أسعار",
      Keys.noMeetingsFound: 'لم يتم العثور على اجتماعات',
      Keys.roomIsEmpty: 'الغرفة فارغة',
      Keys.meetingsHistory: "تاريخ الاجتماعات",
      Keys.history: 'تاريخ',
      Keys.friendList: 'قائمة الاصدقاء',
      Keys.duration: 'مدة',
      Keys.copiedLink: "رابط منسوخ!",
      Keys.share: 'شارك',
      Keys.copy: 'ينسخ',
      Keys.noGuestsFound: "لم يتم العثور على ضيوف",
      Keys.comeAndHangOut: "تعال وتسكع معي على 2i2i",
      Keys.secs: "ثواني",
      Keys.noAccountAdded: "لم تتم إضافة حساب",
      Keys.minSupportIs: "الحد الأدنى للدعم هو",
      Keys.waitLess: "انتظر أقل",
      Keys.weAreWaiting: 'نحن ننتظر!',
      Keys.confirmInWallet: "الرجاء التأكيد في محفظتك",
      Keys.noHostsFound: "لم يتم العثور على مضيفين",
      Keys.pleaseReadCarefully: "الرجاء قراءة بعناية",
      Keys.writeDownRecovery: 'اكتب عبارة مرور الاسترداد (١-٢٥ كلمة). هذا ال',
      Keys.recoverAccount: "الطريقة الوحيدة لاسترداد حسابك في المستقبل.",
      Keys.warning: 'تحذير',
      Keys.doNotShare: "لا تشارك هذه الكلمات مع أي شخص ، لأنها تمنحك حق الوصول الكامل إلى حسابك",
      Keys.createLocalAccount: "إنشاء حساب محلي",
      Keys.createLocalAccountWarning: "لا تشارك هذه الكلمات مع أي شخص ، لأنها تمنحك حق الوصول الكامل إلى حسابك.",
      Keys.recoverAccounts: 'استعادة حساب',
      Keys.recover: 'استعادة',
      Keys.recoverAccountWarning: "املأ جميع المفاتيح الـ 25 الصالحة لحسابك الذي تريد استرداده",
      Keys.verifyRecovery: "التحقق من النسخ الاحتياطي لعبارة مرور الاسترداد",
      Keys.selectWord: "اختر كلمة",
      Keys.complete: 'إكمال',
      Keys.accumulatedSupport: "الدعم المتراكم",
      Keys.startsIn: 'يبدأ في',
      Keys.settled: 'تسوية',
      Keys.waitingGuest: "في انتظار الضيف",
      Keys.pickUpMsg: "الرجاء التقاط",
      Keys.waitingFor: 'انتظر ل',
      Keys.toPickUp: 'للالتقاط',
      Keys.Note: 'ملحوظة',
      Keys.Start: 'يبدأ',
      Keys.connectingHost: "نقوم بتوصيل المضيف ....",
      Keys.connectingGuest: "نحن نربط الضيف .....",
      Keys.whoTop: "من هو الأفضل؟",
      Keys.topSpeeds: "أعلى السرعات",
      Keys.topDurations: "المدد الأعلى",
      Keys.language: "لغة التطبيق",
      Keys.inviteFriend: 'شارك رابط ملفك الشخصي مع متابعيك لمقابلتهم هنا',
      Keys.joinInvite: 'تسكع معي على 2i2i',
      Keys.joinOtherRoom: 'الرجاء الانضمام إلى بعض المضيفين',
      Keys.beFirstJoin: 'كن أول من ينضم إلى هذا المضيف',
      Keys.appVersion: 'الإصدار',
      Keys.logOut: 'تسجيل خروج',
      Keys.connectAccount: "ربط الحساب بـ",
      Keys.updateAvailable: 'التحديث متاح',
      Keys.loginMsg: "كسب النقود من خلال التحدث",
      Keys.loginMsg2: "يوفر 2i2i مساحة آمنة وخاصة للضيوف والمضيفين للالتقاء في شكل مكالمات فيديو",
      Keys.loginMsg3: "> 501 اجتماعات منذ الإطلاق",
      Keys.signInWithGoogle: 'الدخول مع جوجل',
      Keys.signInWithApple: "تسجيل الدخول باستخدام Apple",
      Keys.signInWithTwitter: "تسجيل الدخول باستخدام Twitter",
      Keys.signInAnonymously: 'الدخول بتخفي',
      Keys.searchFaq: 'كلمات البحث',
      Keys.noInternetTitle: 'لا يوجد اتصال بالإنترنت',
      Keys.noInternetMessage: 'أنت غير متصل بالإنترنت. تأكد من تشغيل WI-FI. تم إيقاف وضع الطائرة وحاول مرة أخرى',
      Keys.loading: 'جار التحميل...',
      Keys.noKeyFound: "لا يمكننا العثور على حساب من هذه المفاتيح",
      Keys.transactionConfirmMsg: 'هل أنت متأكد من إجراء المعاملة من محفظتك؟',
      Keys.no: 'رقم',
      Keys.yes: 'نعم',
      Keys.pleaseConfirm: 'يرجى تأكيد',
      Keys.okay: 'حسنا',
      Keys.connectedSocialAccount: 'متصل بحساب اجتماعي',
      Keys.zero: 'صفر',
      Keys.minutes: 'الدقائق',
      Keys.hours: 'ساعات',
      Keys.days: 'أيام',
      Keys.weeks: 'أسابيع',
      Keys.months: 'الشهور',
      Keys.years: 'سنوات',
      Keys.thisIsYou: 'هذا هو أنت',
      Keys.deleteAccount: 'حذف الحساب',
      Keys.deleteAccountMessage: 'هل تريد بالتأكيد حذف حسابك نهائيًا من 2i2i؟',
      Keys.estMaxDuration: 'المدة القصوى',
      Keys.waitTimeMsg: 'EST. وقت الانتظار هو',
      Keys.writeComment: 'أكتب تعليقا...',
      Keys.connecting: 'توصيل...',
      Keys.muted: 'كتم الصوت',
      Keys.walletConnect: 'Wallet Connect',
      Keys.connect: 'الاتصال',
      Keys.receiveSendCoin: 'يرجى أولا ربط حساب لإرسال / استقبال العملات.',
      Keys.cantBidUser: 'لا يمكنك المزايدة لهذا المستخدم',
      Keys.miniSupport: 'السرعة الدنيا أكبر من الحد الأقصى للدعم',
      Keys.noWalletFound: 'لم يتم العثور على حساب المحفظة.',
      Keys.someOneTalk: 'شخص ما يريد التحدث معك',
      Keys.openApp: 'فتح',
      Keys.connectWallet: 'ربط المحفظة',
      Keys.walletDesMsg1:
          'لتلقي العملات المعدنية ، تحتاج إلى ربط حساب. انقر فوق Connect to لتوصيل حساب WalletConnect في تطبيق محفظتك. بعد ذلك ارجع إلى 2i2i.',
      Keys.walletDesMsg2: 'لقد قمت بتوصيل حساب. الآن يمكنك الحصول على عملات معدنية. انقر فوق التحدث للتواصل مع الضيف الخاص بك.',
      Keys.acceptBid: 'قبول العطاء',
      Keys.startTalk: 'ابدأ الحديث',
      Keys.failToConnect: 'فشل في الاتصال. حاول مرة اخرى.',
      Keys.retry: 'أعد المحاولة',
    };
  }
}
