import '../../../infrastructure/commons/keys.dart';

class ar{
  Map data(){
    return {
      Keys.aboutYou: 'About you',
      Keys.aboutYouDesc: 'Please fill this out',
      Keys.faq: 'FAQ',
      Keys.automatic: 'Automatic',
      Keys.shareQr: 'Share yourself',
      Keys.error: 'Error',
      Keys.errorWhileAddBid: 'Error while adding bid, Try another account or reduce the max duration or reduce the speed',
      Keys.less: 'less',
      Keys.forever: 'forever',
      Keys.minSpeed: 'Min Support',
      Keys.maxDuration: 'Max Duration',
      Keys.numberHint: 'Enter real number like 12',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'μALGO/sec',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: 'Invalid',
      Keys.join: 'Join',
      Keys.favorites: 'Favorites',
      Keys.wallet: 'Wallet',
      Keys.blockList: 'Blocked Guests',
      Keys.favList: 'Favorite List',
      Keys.fav: 'Favorites',
      Keys.scanQr: 'Scan QR',
      Keys.about: 'About',
      Keys.aboutPageUrl: 'https://shorturl.at/hilqL',
      Keys.scanInWalletConnect: 'Use WalletConnect\n(e.g. Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: 'OK',
      Keys.talk: 'Talk',
      Keys.cancel: 'Cancel',
      Keys.close: 'Close',
      Keys.copyMessage: 'Copied to Clipboard',
      Keys.userBusyMessage: 'User is Offline or Busy..',
      Keys.logout: 'Logout',
      Keys.logoutAreYouSure: 'Are you sure that you want to logout?',
      Keys.logoutFailed: 'Logout failed',
      Keys.signIn: 'Sign in',
      Keys.signInWithEmailPassword: 'Sign in with email and password',
      Keys.goAnonymous: 'Go anonymous',
      Keys.or: 'or',
      Keys.signInFailed: 'Sign in failed',
      Keys.homePage: 'Home Page',
      Keys.home: 'Search',
      Keys.account: 'Profile',
      Keys.doneIHaveCopied: 'Done and copied',
      Keys.profile: 'Host',
      Keys.settings: 'Settings',
      Keys.searchUserHint: 'Find a Host',
      Keys.search: 'Search',
      Keys.myAccount: 'My Account',
      Keys.bidsIn: 'Bids In',
      Keys.bidsInPage: 'Bids In Page',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: 'New Card',
      Keys.createABid: 'Join the queue',
      Keys.algoSec: 'μALGO/s',
      Keys.speed: 'Support',
      Keys.bidAmount: 'Bid Amount',
      Keys.note: 'Note (optional)',
      Keys.bidNote: 'Say something awesome',
      Keys.yourBioHint: 'I love to #talk and #cook\nI can #teach',
      Keys.yourNameHint: 'My cool name',
      Keys.writeYourBio: 'Write your bio',
      Keys.writeYourName: 'Write your name',
      Keys.bioExample: 'Ex: Let\'s talk about #cooking or #basketball',
      Keys.save: 'Save',
      Keys.required: 'Required',
      Keys.enterValidData: 'Please enter valid data',
      Keys.setUpAccount: 'Who are you?',
      Keys.hangoutSettings: 'Host Settings',
      Keys.userName: 'Username',
      Keys.name: 'Username',
      Keys.bio: 'Your interests (use hashtags)',
      Keys.addAccount: 'Add account',
      Keys.walletAccount: 'Wallet account',
      Keys.walletAccountMsg: 'I want to connect a 3rd party wallet',
      Keys.recoverPassphrase: 'Recover with passphrase',
      Keys.recoverPassPhaseMsg: 'I know the 25 secret words',
      Keys.addLocalAccount: 'Add local account',
      Keys.addLocalAccountMsg: 'Create a local account on this device',
      Keys.estMaxDuration: 'Max duration',
      Keys.swipeAndChangeAccount: 'Swipe to change account',
      Keys.insufficientBalance: 'Insufficient balance',
      Keys.addBid: 'Join',
      Keys.copyAndNext: 'Copy and Next',
      Keys.report: 'Report',
      Keys.block: 'Block',
      Keys.unBlock: 'Unblock',
      Keys.seeMore: 'see more',
      Keys.appRatingTitle: 'Did you like this meeting?',
      Keys.appRatingMessage: 'Any feedback?',
      Keys.appRatingSubmitButton: 'Submit',
      Keys.selectNetworkMode: 'Select Network Mode:',
      Keys.themeMode: 'Color Scheme:',
      Keys.myProfile: 'My Profile',
      Keys.bidIn: 'Bid in',
      Keys.bidOut: 'Waiting',
      Keys.noBidFound: 'No bids found',
      Keys.meetingsHistory: 'Meetings History',
      Keys.history: 'History',
      Keys.friendList: 'Friend list',
    };
  }
}