import '../../../infrastructure/commons/keys.dart';

class de {
  Map data() {
    return {
      Keys.aboutYou: 'Über dich',
      Keys.aboutYouDesc: 'Bitte füllen Sie das aus',
      Keys.faq: 'FAQ',
      Keys.automatic: 'Automatisch',
      Keys.shareQr: 'Teile dich',
      Keys.error: 'Fehler',
      Keys.errorWhileAddBid: 'Fehler beim Hinzufügen des Gebots, versuchen Sie es mit einem anderen Konto oder reduzieren Sie die maximale Dauer oder reduzieren Sie die Geschwindigkeit',
      Keys.less: 'weniger',
      Keys.importance: 'Bedeutung',
      Keys.chrony: 'Chronik',
      Keys.highRoller: 'HighRoller',
      Keys.theme: 'Thema',
      Keys.light: 'Hell',
      Keys.dark: 'Dunkel',
      Keys.auto: 'Auto',
      Keys.forever: 'bis in alle Ewigkeit',
      Keys.minSpeed: 'Min. Unterstützung',
      Keys.maxDuration: 'Maximale Dauer',
      Keys.estWaitTime: 'Europäische Sommerzeit. Wartezeit ist',
      Keys.numberHint: 'Geben Sie eine reelle Zahl wie 12 ein',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'ALGO/s',
      Keys.ALGO: 'ALGO',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: 'Ungültig',
      Keys.join: 'Beitreten',
      Keys.favorites: 'Favoriten',
      Keys.wallet: 'Brieftasche',
      Keys.blockList: 'Blockierte Gäste',
      Keys.favList: 'Favoritenliste',
      Keys.fav: 'Favoriten',
      Keys.scanQr: 'QR scannen',
      Keys.about: 'Etwa',
      Keys.aboutPageUrl: 'https://about.2i2i.app',
      Keys.scanInWalletConnect: 'WalletConnect verwenden\n(z. B. Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: 'OK',
      Keys.talk: 'Sprechen',
      Keys.cancel: 'Abbrechen',
      Keys.ratings: 'Bewertungen',
      Keys.close: 'Nah dran',
      Keys.copyMessage: 'In die Zwischenablage kopiert',
      Keys.userBusyMessage: 'Benutzer ist offline oder beschäftigt..',
      Keys.logout: 'Ausloggen',
      Keys.noRatingsFound: 'Keine Bewertungen gefunden',
      Keys.logoutAreYouSure: 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      Keys.logoutFailed: 'Abmeldung fehlgeschlagen',
      Keys.signIn: 'Anmelden',
      Keys.signInWithEmailPassword: 'Mit E-Mail und Passwort anmelden',
      Keys.goAnonymous: 'Anonym bleiben',
      Keys.or: 'oder',
      Keys.signInFailed: 'Anmeldung fehlgeschlagen',
      Keys.somethingWantWrong: 'Etwas will falsch',
      Keys.homePage: 'Startseite',
      Keys.home: 'Suche',
      Keys.account: 'Profil',
      Keys.doneIHaveCopied: 'Fertig und kopiert',
      Keys.profile: 'Gastgeber',
      Keys.settings: 'Einstellungen',
      Keys.searchUserHint: 'Finden Sie einen Gastgeber',
      Keys.search: 'Suche',
      Keys.myAccount: 'Mein Konto',
      Keys.bidsIn: 'Gebote ein',
      Keys.bidsInPage: 'Gebote auf der Seite',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: 'Neue Karte',
      Keys.createABid: 'Tritt dem Gastgeber bei',
      Keys.speed: 'Unterstützung',
      Keys.bidAmount: 'Gebotsbetrag',
      Keys.note: 'Hinweis (optional)',
      Keys.bidNote: 'Sag etwas Tolles',
      Keys.yourBioHint: 'Ich liebe es zu #reden und #kochen\nIch kann #lehren',
      Keys.yourNameHint: 'Mein cooler Name',
      Keys.writeYourBio: 'Schreiben Sie Ihre Biografie',
      Keys.writeYourName: 'Schreibe Deinen Namen',
      Keys.bioExample: 'Bsp.: Reden wir über #Kochen oder #Basketball',
      Keys.save: 'Speichern',
      Keys.required: 'Erforderlich',
      Keys.enterValidData: 'Bitte gültige Daten eingeben',
      Keys.setUpAccount: 'Wer bist du?',
      Keys.userSettings: 'Host-Einstellungen',
      Keys.userName: 'Nutzername',
      Keys.name: 'Nutzername',
      Keys.bio: 'Ihre Interessen (verwenden Sie Hashtags)',
      Keys.addAccount: 'Konto hinzufügen',
      Keys.walletAccount: 'Wallet-Konto',
      Keys.walletAccountMsg: 'Ich möchte eine Wallet eines Drittanbieters verbinden',
      Keys.recoverPassphrase: 'Mit Passphrase wiederherstellen',
      Keys.recoverPassPhaseMsg: 'Ich kenne die 25 geheimen Wörter',
      Keys.addLocalAccount: 'Lokales Konto hinzufügen',
      Keys.addLocalAccountMsg: 'Ein lokales Konto auf diesem Gerät erstellen',
      Keys.swipeAndChangeAccount: 'Zum Kontowechsel wischen',
      Keys.insufficientBalance: 'Mangelhaftes Gleichgewicht',
      Keys.addBid: 'Beitreten',
      Keys.next: 'weiter',
      Keys.report: 'Prüfbericht',
      Keys.block: 'Block',
      Keys.unBlock: 'Entsperren',
      Keys.seeMore: 'Mehr sehen',
      Keys.more: 'Mehr',
      Keys.appRatingTitle: 'Hat Ihnen dieses Treffen gefallen?',
      Keys.appRatingMessage: 'Irgendeine Anregung?',
      Keys.appRatingSubmitButton: 'Einreichen',
      Keys.selectNetworkMode: 'Netzwerkmodus auswählen:',
      Keys.themeMode: 'Farbschema:',
      Keys.myProfile: 'Mein Profil',
      Keys.bidIn: 'Mitbieten',
      Keys.bidOut: 'Warten',
      Keys.noBidFound: 'Keine Gebote gefunden',
      Keys.noMeetingsFound: 'Keine Besprechungen gefunden',
      Keys.roomIsEmpty: 'So leer',
      Keys.meetingsHistory: 'Besprechungsverlauf',
      Keys.history: 'Geschichte',
      Keys.friendList: 'Freundesliste',
      Keys.duration: 'Dauer',
      Keys.copiedLink: 'Link kopiert!',
      Keys.share: 'Teilen',
      Keys.copy: 'Kopieren',
      Keys.noGuestsFound: 'Keine Gäste gefunden',
      Keys.comeAndHangOut: 'Komm und häng mit mir auf 2i2i ab',
      Keys.secs: 'Sekunden',
      Keys.noAccountAdded: 'Kein Konto hinzugefügt',
      Keys.minSupportIs: 'Mindestunterstützung ist',
      Keys.waitLess: 'Weniger warten',
      Keys.weAreWaiting: 'Wir warten!',
      Keys.confirmInWallet: 'Bitte in Ihrer Brieftasche bestätigen',
      Keys.noHostsFound: 'Keine Hosts gefunden',
      Keys.pleaseReadCarefully: 'Bitte aufmerksam lesen',
      Keys.writeDownRecovery: 'Schreiben Sie Ihre Wiederherstellungs-Passphrase auf (1-25 Wörter). Dies ist das',
      Keys.recoverAccount: 'einzige Möglichkeit, Ihr Konto in Zukunft wiederherzustellen.',
      Keys.warning: 'Warnung',
      Keys.doNotShare: 'Teilen Sie diese Wörter mit niemandem, da dies vollen Zugriff auf Ihr Konto gewährt',
      Keys.createLocalAccount: 'Lokales Konto erstellen',
      Keys.createLocalAccountWarning: 'Teilen Sie diese Wörter mit niemandem, da Sie dadurch vollen Zugriff auf Ihr Konto erhalten.',
      Keys.recoverAccounts: 'Account wiederherstellen',
      Keys.recover: 'Genesen',
      Keys.recoverAccountWarning: 'Füllen Sie alle 25 gültigen Schlüssel Ihres Kontos ein, die Sie wiederherstellen möchten',
      Keys.verifyRecovery: 'Sicherung der Wiederherstellungs-Passphrase überprüfen',
      Keys.selectWord: 'Wort auswählen',
      Keys.complete: 'Vollständig',
      Keys.accumulatedSupport: 'kumulierte Unterstützung',
      Keys.startsIn: 'Beginnt in',
      Keys.settled: 'Erledigt',
      Keys.waitingGuest: 'Warten als Gast',
      Keys.pickUpMsg: 'Bitte abholen für',
      Keys.waitingFor: 'Warten auf',
      Keys.toPickUp: 'abholen',
      Keys.Note: 'Notiz',
      Keys.Start: 'Anfang',
      Keys.connectingHost: 'Wir verbinden den Host....',
      Keys.connectingGuest: 'Wir verbinden den Gast.....',
      Keys.whoTop: 'Wer ist oben?',
      Keys.topSpeeds: 'Höchstgeschwindigkeiten',
      Keys.topDurations: 'Top-Dauern',
      Keys.language: 'App-Sprache',
      Keys.inviteFriend: 'Teilen Sie Ihren Profillink mit Ihren Followern, um sie hier zu treffen',
      Keys.joinInvite: 'Hang out with me on 2i2i',
      Keys.joinOtherRoom: 'Bitte schließen Sie sich einigen Hosts an',
      Keys.beFirstJoin: 'Seien Sie der Erste, der diesem Host beitritt',
      Keys.appVersion:'Ausführung',
      Keys.logOut: 'AUSLOGGEN',
      Keys.connectAccount: 'Konto verbinden mit',
      Keys.updateAvailable: 'Update verfügbar',
      Keys.loginMsg: 'Das Uber des Redens',
      Keys.loginMsg2: '2i2i bietet Gästen und Gastgebern einen sicheren und privaten Ort, an dem sie sich in Form von Videoanrufen treffen können',
      Keys.loginMsg3: '>501 MEETINGS SEIT DEM START',
      Keys.signInWithGoogle: 'Anmeldung mit Google',
      Keys.signInWithApple: 'Mit Apple anmelden',
      Keys.signInWithTwitter:   'Mit Twitter anmelden',
      Keys.signInAnonymously: 'Anonym anmelden',
      Keys.searchFaq: 'Suche Schlüsselwörter',
      Keys.loading:'Wird geladen...'
    };
  }
}
