import '../../../infrastructure/commons/keys.dart';

class en {
  Map data() {
    return {
      Keys.aboutYou: 'About you',
      Keys.aboutYouDesc: 'Please fill this out',
      Keys.faq: 'FAQ',
      Keys.automatic: 'Automatic',
      Keys.shareQr: 'Share yourself',
      Keys.error: 'Error',
      Keys.errorWhileAddBid:
          'Error while adding bid, Try another account or reduce the max duration or reduce the speed',
      Keys.less: 'less',
      Keys.importance: 'Importance',
      Keys.chrony: 'Chrony',
      Keys.highRoller: 'HighRoller',
      Keys.theme: 'Theme',
      Keys.light: 'Light',
      Keys.dark: 'Dark',
      Keys.auto: 'Auto',
      Keys.forever: 'forever',
      Keys.minSpeed: 'Min Support',
      Keys.maxDuration: 'Max Duration',
      Keys.estWaitTime: 'Est. Wait Time is',
      Keys.numberHint: 'Enter real number like 12',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'μALGO/sec',
      Keys.ALGO: 'ALGO',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: 'Invalid',
      Keys.join: 'Join',
      Keys.favorites: 'Favorites',
      Keys.wallet: 'Wallet',
      Keys.blockList: 'Blocked Guests',
      Keys.favList: 'Favorite List',
      Keys.fav: 'Favorites',
      Keys.scanQr: 'Scan QR',
      Keys.about: 'About',
      Keys.aboutPageUrl: 'https://about.2i2i.app',
      Keys.scanInWalletConnect: 'Use WalletConnect\n(e.g. Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: 'OK',
      Keys.talk: 'Talk',
      Keys.cancel: 'Cancel',
      Keys.ratings: 'Ratings',
      Keys.close: 'Close',
      Keys.copyMessage: 'Copied to Clipboard',
      Keys.userBusyMessage: 'User is Offline or Busy..',
      Keys.logout: 'Logout',
      Keys.noRatingsFound: 'No ratings found',
      Keys.logoutAreYouSure: 'Are you sure that you want to logout?',
      Keys.logoutFailed: 'Logout failed',
      Keys.signIn: 'Sign in',
      Keys.signInWithEmailPassword: 'Sign in with email and password',
      Keys.goAnonymous: 'Go anonymous',
      Keys.or: 'or',
      Keys.signInFailed: 'Sign in failed',
      Keys.somethingWantWrong: 'Something went wrong',
      Keys.homePage: 'Home Page',
      Keys.home: 'Search',
      Keys.account: 'Profile',
      Keys.doneIHaveCopied: 'Done and copied',
      Keys.profile: 'Host',
      Keys.settings: 'Settings',
      Keys.searchUserHint: 'Find a Host',
      Keys.search: 'Search',
      Keys.myAccount: 'My Account',
      Keys.bidsIn: 'Bids In',
      Keys.bidsInPage: 'Bids In Page',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: 'New Card',
      Keys.createABid: 'Join the queue',
      Keys.algoSec: 'μALGO/s',
      Keys.speed: 'Support',
      Keys.bidAmount: 'Bid Amount',
      Keys.note: 'Note (optional)',
      Keys.bidNote: 'Say something awesome',
      Keys.yourBioHint: 'I love to #talk and #cook\nI can #teach',
      Keys.yourNameHint: 'My cool name',
      Keys.writeYourBio: 'Write your bio',
      Keys.writeYourName: 'Write your name',
      Keys.bioExample: 'Ex: Let\'s talk about #cooking or #basketball',
      Keys.save: 'Save',
      Keys.required: 'Required',
      Keys.enterValidData: 'Please enter valid data',
      Keys.setUpAccount: 'Who are you?',
      Keys.userSettings: 'Host Settings',
      Keys.userName: 'Username',
      Keys.name: 'Username',
      Keys.bio: 'Your interests (use hashtags)',
      Keys.addAccount: 'Add account',
      Keys.walletAccount: 'Wallet account',
      Keys.walletAccountMsg: 'I want to connect a 3rd party wallet',
      Keys.recoverPassphrase: 'Recover with passphrase',
      Keys.recoverPassPhaseMsg: 'I know the 25 secret words',
      Keys.addLocalAccount: 'Add local account',
      Keys.addLocalAccountMsg: 'Create a local account on this device',
      Keys.swipeAndChangeAccount: 'Swipe to change account',
      Keys.insufficientBalance: 'Insufficient balance',
      Keys.addBid: 'Join',
      Keys.next: 'Next',
      Keys.report: 'Report',
      Keys.block: 'Block',
      Keys.unBlock: 'Unblock',
      Keys.seeMore: 'see more',
      Keys.more: 'More',
      Keys.appRatingTitle: 'Did you like this meeting?',
      Keys.appRatingMessage: 'Any feedback?',
      Keys.appRatingSubmitButton: 'Submit',
      Keys.selectNetworkMode: 'Select Network Mode:',
      Keys.themeMode: 'Color Scheme:',
      Keys.myProfile: 'My Profile',
      Keys.bidIn: 'Bid in',
      Keys.bidOut: 'Waiting',
      Keys.noBidFound: 'No bids found',
      Keys.noMeetingsFound: 'No meetings found',
      Keys.roomIsEmpty: 'Your room is empty',
      Keys.meetingsHistory: 'Meetings History',
      Keys.history: 'History',
      Keys.friendList: 'Friend list',
      Keys.duration: 'Duration',
      Keys.copiedLink: 'Copied Link!',
      Keys.share: 'Share',
      Keys.copy: 'Copy',
      Keys.noGuestsFound: 'No Guests found',
      Keys.comeAndHangOut: 'Come and hang out with me on 2i2i',
      Keys.secs: 'secs',
      Keys.noAccountAdded: 'No account added',
      Keys.minSupportIs: 'Min support is',
      Keys.waitLess: 'Wait Less',
      Keys.weAreWaiting: 'We are waiting!',
      Keys.confirmInWallet: 'Please confirm in your wallet',
      Keys.noHostsFound: 'No Hosts found',
      Keys.pleaseReadCarefully: 'Please read carefully',
      Keys.writeDownRecovery:
          'Write down your recovery passphrase(1-25 words). This is the',
      Keys.recoverAccount: 'only way to recover your account in future.',
      Keys.warning: 'Warning',
      Keys.doNotShare:
          'Do not share these words with anyone, as it grants full access to your account',
      Keys.createLocalAccount: 'Create Local Account',
      Keys.createLocalAccountWarning:
          'Do not share these words with anyone, as it grants full access to your account.',
      Keys.recoverAccounts: 'Recover account',
      Keys.recover: 'Recover',
      Keys.recoverAccountWarning:
          'Fill all 25 valid keys of your account that you want to recover',
      Keys.verifyRecovery: 'Verify recovery passphrase backup',
      Keys.selectWord: 'Select word',
      Keys.complete: 'Complete',
      Keys.accumulatedSupport: 'Accumulated support',
      Keys.startsIn: 'Starts in',
      Keys.settled: 'Settled',
      Keys.waitingGuest: 'Waiting as a Guest',
      Keys.pickUpMsg: 'Please pick up for',
      Keys.waitingFor: 'Waiting for',
      Keys.toPickUp: 'to pick up',
      Keys.Note: 'Note',
      Keys.Start: 'Start',
      Keys.connectingHost: 'We are connecting the Host....',
      Keys.connectingGuest: 'We are connecting the Guest.....',
      Keys.whoTop: 'Who\’s Top?',
      Keys.topSpeeds: 'Top Speeds',
      Keys.topDurations: 'Top Durations',
      Keys.language: 'App Language',
      Keys.inviteFriend:
          'Share your profile link with\nyour followers to meet them here',
      Keys.joinInvite: 'Hang out with me on 2i2i',
      Keys.joinOtherRoom: 'Please join some people\'s rooms',
      Keys.beFirstJoin: 'Be the first to join this room',
      Keys.appVersion: 'Version',

      Keys.logOut: 'LOGOUT',
      Keys.connectAccount: 'Connect account with',
      Keys.updateAvailable: 'Update Available',
      Keys.loginMsg: 'The place for you to Hangout',
      Keys.loginMsg2: '2i2i provides a safe and private space for Guests and Host to meet in the form of video calls',
      Keys.loginMsg3: '>306 MEETINGS SINCE LAUNCH',
      Keys.signInWithGoogle: 'Sign in with Google',
      Keys.signInWithApple: 'Sign in with Apple',
      Keys.signInWithTwitter:  'Sign in with Twitter',
      Keys.signInAnonymously: 'Sign in Anonymously',
      Keys.searchFaq: 'Search keywords',
      Keys.noInternetTitle: 'No Internet Connection',
      Keys.noInternetMessage: 'You are not connected to the internet. Make sure WI-FI is on. Airplane Mode is off and try again',

      Keys.loading:'Loading...'

    };
  }
}
