import '../../../infrastructure/commons/keys.dart';

class es {
  Map data() {
    return {
      Keys.aboutYou: 'Sobre ti',
      Keys.aboutYouDesc: 'Llénelo, por favor',
      Keys.faq: 'Preguntas más frecuentes',
      Keys.automatic: 'Automático',
      Keys.shareQr: 'Compártete',
      Keys.error: 'Error',
      Keys.errorWhileAddBid: 'Error al agregar oferta, pruebe con otra cuenta o reduzca la duración máxima o reduzca la velocidad',
      Keys.less: 'menos',
      Keys.importance: 'Importancia',
      Keys.chrony: 'cronista',
      Keys.highRoller: 'Rodillo alto',
      Keys.theme: 'Tema',
      Keys.light: 'Ligero',
      Keys.dark: 'Oscuro',
      Keys.auto: 'Auto',
      Keys.forever: 'siempre',
      Keys.minSpeed: 'Soporte mínimo',
      Keys.maxDuration: 'Duración máxima',
      Keys.estWaitTime: 'Est. tiempo de espera es',
      Keys.numberHint: 'Ingrese un número real como 12',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'ALGO/s',
      Keys.ALGO: 'ALGO',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: 'Inválido',
      Keys.join: 'Entrar',
      Keys.favorites: 'Favoritos',
      Keys.wallet: 'Cartera',
      Keys.blockList: 'Invitados bloqueados',
      Keys.favList: 'Lista favorita',
      Keys.fav: 'Favoritos',
      Keys.scanQr: 'Escanear QR',
      Keys.about: 'Sobre',
      Keys.aboutPageUrl: 'https://about.2i2i.app',
      Keys.scanInWalletConnect: 'Usar WalletConnect\n(e.g. Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: 'OK',
      Keys.talk: 'Hablar',
      Keys.cancel: 'Cancelar',
      Keys.ratings: 'Calificaciones',
      Keys.close: 'Cerrar',
      Keys.copyMessage: 'Copiado al portapapeles',
      Keys.userBusyMessage: 'El usuario está fuera de línea u ocupado..',
      Keys.logout: 'Cerrar sesión',
      Keys.noRatingsFound: 'No se encontraron calificaciones',
      Keys.logoutAreYouSure: '¿Estás seguro de que quieres cerrar sesión?',
      Keys.logoutFailed: 'Cierre de sesión fallido',
      Keys.signIn: 'Registrarse',
      Keys.signInWithEmailPassword: 'Iniciar sesión con correo electrónico y contraseña',
      Keys.goAnonymous: 'Ir anónimo',
      Keys.or: 'o',
      Keys.signInFailed: 'Fallo al iniciar sesion',
      Keys.somethingWantWrong: 'Algo salió mal',
      Keys.homePage: 'Página de inicio',
      Keys.home: 'Buscar',
      Keys.account: 'Perfil',
      Keys.doneIHaveCopied: 'Listo y copiado',
      Keys.profile: 'Anfitrión',
      Keys.settings: 'Ajustes',
      Keys.searchUserHint: 'Encuentra un anfitrión',
      Keys.search: 'Buscar',
      Keys.myAccount: 'Mi cuenta',
      Keys.bidsIn: 'Pujas en',
      Keys.bidsInPage: 'Ofertas en la página',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: 'Nueva tarjeta',
      Keys.createABid: 'Únete a la anfitriona',
      Keys.speed: 'Apoyo',
      Keys.bidAmount: 'Monto de la oferta',
      Keys.note: 'Nota (opcional)',
      Keys.bidNote: 'Di algo genial',
      Keys.yourBioHint: 'Me encanta #hablar y #cocinar\nYo puedo #enseñar',
      Keys.yourNameHint: 'Mi nombre genial',
      Keys.writeYourBio: 'Escribe tu biografía',
      Keys.writeYourName: 'Escribe tu nombre',
      Keys.bioExample: 'Ej: Hablemos de #cocina o #baloncesto',
      Keys.save: 'Guardar',
      Keys.required: 'Requerido',
      Keys.enterValidData: 'Por favor ingrese datos válidos',
      Keys.setUpAccount: '¿Quién eres tú?',
      Keys.userSettings: 'Configuración del anfitrión',
      Keys.userName: 'Nombre de usuario',
      Keys.name: 'Nombre de usuario',
      Keys.bio: 'Tus intereses (usa hashtags)',
      Keys.addAccount: 'Añadir cuenta',
      Keys.walletAccount: 'Cuenta de billetera',
      Keys.walletAccountMsg: 'Quiero conectar una billetera de terceros',
      Keys.recoverPassphrase: 'Recuperar con frase de contraseña',
      Keys.recoverPassPhaseMsg: 'Conozco las 25 palabras secretas.',
      Keys.addLocalAccount: 'Agregar cuenta local',
      Keys.addLocalAccountMsg: 'Crear una cuenta local en este dispositivo',
      Keys.swipeAndChangeAccount: 'Desliza para cambiar de cuenta',
      Keys.insufficientBalance: 'Saldo insuficiente',
      Keys.addBid: 'Entrar',
      Keys.next: 'Siguiente',
      Keys.report: 'Reporte',
      Keys.block: 'Bloquear',
      Keys.unBlock: 'Desbloquear',
      Keys.seeMore: 'ver más',
      Keys.more: 'Más',
      Keys.appRatingTitle: '¿Te gustó este encuentro?',
      Keys.appRatingMessage: '¿Cualquier retroalimentación?',
      Keys.appRatingSubmitButton: 'Entregar',
      Keys.selectNetworkMode: 'Seleccione el modo de red:',
      Keys.themeMode: 'Esquema de colores:',
      Keys.myProfile: 'Mi perfil',
      Keys.bidIn: 'Pujar en',
      Keys.bidOut: 'Esperando',
      Keys.noBidFound: 'No se encontraron ofertas',
      Keys.noMeetingsFound: 'No se encontraron reuniones',
      Keys.roomIsEmpty: 'la habitación está vacía',
      Keys.meetingsHistory: 'Historial de reuniones',
      Keys.history: 'Historia',
      Keys.friendList: 'Lista de amigos',
      Keys.duration: 'Duración',
      Keys.copiedLink: 'Enlace copiado!',
      Keys.share: 'Cuota',
      Keys.copy: 'Copiar',
      Keys.noGuestsFound: 'No se encontraron invitados',
      Keys.comeAndHangOut: 'Ven y pasa el rato conmigo en 2i2i',
      Keys.secs: 'segundos',
      Keys.noAccountAdded: 'Ninguna cuenta agregada',
      Keys.minSupportIs: 'El soporte mínimo es',
      Keys.waitLess: 'Espera menos',
      Keys.weAreWaiting: 'Nosotros estamos esperando',
      Keys.confirmInWallet: 'Por favor confirme en su billetera',
      Keys.noHostsFound: 'No se encontraron anfitriones',
      Keys.pleaseReadCarefully: 'Por favor lea cuidadosamente',
      Keys.writeDownRecovery: 'Escriba su frase de contraseña de recuperación (1-25 palabras). Esto es la',
      Keys.recoverAccount: 'única manera de recuperar su cuenta en el futuro.',
      Keys.warning: 'Advertencia',
      Keys.doNotShare: 'No comparta estas palabras con nadie, ya que otorga acceso completo a su cuenta',
      Keys.createLocalAccount: 'Crear cuenta local',
      Keys.createLocalAccountWarning: 'No comparta estas palabras con nadie, ya que otorga acceso completo a su cuenta.',
      Keys.recoverAccounts: 'Recuperar cuenta',
      Keys.recover: 'Recuperar',
      Keys.recoverAccountWarning: 'Complete las 25 claves válidas de su cuenta que desea recuperar',
      Keys.verifyRecovery: 'Verifique la copia de seguridad de la frase de contraseña de recuperación',
      Keys.selectWord: 'Seleccionar palabra',
      Keys.complete: 'Completo',
      Keys.accumulatedSupport: 'Apoyo acumulado',
      Keys.startsIn: 'Empieza en',
      Keys.settled: 'Establecido',
      Keys.waitingGuest: 'Esperando como invitado',
      Keys.pickUpMsg: 'Por favor, recoja para',
      Keys.waitingFor: 'Esperando',
      Keys.toPickUp: 'recoger',
      Keys.Note: 'Nota',
      Keys.Start: 'Comienzo',
      Keys.connectingHost: 'Nosotros estamos conectando el Anfitrión ....',
      Keys.connectingGuest: 'Estamos conectando al invitado .....',
      Keys.whoTop: 'Quien es el superior',
      Keys.topSpeeds: 'Velocidades máximas',
      Keys.topDurations: 'Duraciones principales',
      Keys.language: 'Idioma de la aplicación',
      Keys.inviteFriend:
          'Comparte el enlace de tu perfil con tus seguidores para conocerlos aquí',
      Keys.joinInvite: 'Tu amigo e invita a unirte a 2i2i',
      Keys.joinOtherRoom: 'Únase a algunos anfitriones',
      Keys.beFirstJoin: 'Sé el primero en unirte a este Host',
      Keys.appVersion: 'Versión',
      Keys.logOut: 'CERRAR SESIÓN',
      Keys.connectAccount: 'Conectar cuenta con',
      Keys.updateAvailable: 'Actualización disponible',
      Keys.loginMsg: 'gana monedas hablando',
      Keys.loginMsg2:
          '2i2i proporciona un espacio seguro y privado para que los Huéspedes y el Anfitrión se reúnan en forma de videollamadas',
      Keys.loginMsg3: '>501 REUNIONES DESDE EL LANZAMIENTO',
      Keys.signInWithGoogle: 'Inicia sesión con Google',
      Keys.signInWithApple: 'Iniciar sesión con Apple',
      Keys.signInWithTwitter: 'Registrate con Twitter',
      Keys.signInAnonymously: 'Iniciar sesión en forma anónima',
      Keys.searchFaq: 'Buscar palabras clave',
      Keys.noInternetTitle: 'Sin conexión a Internet',
      Keys.noInternetMessage: 'No estás conectado a Internet. Asegúrate de que el WI-FI esté encendido. El modo avión está desactivado e inténtalo de nuevo',
      Keys.loading: 'Cargando...',
      Keys.noKeyFound: 'No podemos encontrar la cuenta de estas claves',
      Keys.no: 'no',
      Keys.yes: 'sí',
      Keys.transactionConfirmMsg: '¿Estás segura de hacer la transacción desde tu billetera?',
      Keys.pleaseConfirm: 'Por favor confirmar',
      Keys.okay: 'okey',
      Keys.connectedSocialAccount: 'Conectado con cuenta social',
      Keys.zero: 'cero',
      Keys.minutes: 'minutos',
      Keys.hours: 'horas',
      Keys.days: 'días',
      Keys.weeks: 'semanas',
      Keys.months: 'meses',
      Keys.years: 'años',
      Keys.thisIsYou: 'Este Eres tu',
      Keys.deleteAccount: 'Borrar cuenta',
      Keys.deleteAccountMessage: '¿Está seguro de que desea eliminar su cuenta de forma permanente de 2i2i?',
      Keys.estMaxDuration: 'Duración máxima',
      Keys.waitTimeMsg: 'Est. el tiempo de espera es',
      Keys.writeComment: 'Escribir un comentario...',
      Keys.connecting: 'Conectando...',
      Keys.muted: 'Apagado',
      Keys.walletConnect: 'Monedero Conectar',
      Keys.connect: 'Conectar',
      Keys.receiveSendCoin: 'Primero conecte una cuenta para enviar/recibir monedas.',
      Keys.cantBidUser: 'No puedes pujar por este usuario',
      Keys.miniSupport: 'La velocidad mínima es mayor que el soporte máximo',
      Keys.noWalletFound: 'No se encontró ninguna cuenta de billetera.',
      Keys.someOneTalk: 'Alguien quiere hablar contigo',
    };
  }
}
