import '../../../infrastructure/commons/keys.dart';

class ko {
  Map data() {
    return {
      Keys.aboutYou: '당신에 대해',
      Keys.aboutYouDesc: '이 내용을 작성해 주세요',
      Keys.faq: '자주하는 질문',
      Keys.automatic: '자동적 인',
      Keys.shareQr: '자신을 공유',
      Keys.error: '오류',
      Keys.errorWhileAddBid: '입찰가를 추가하는 동안 오류가 발생했습니다. 다른 계정을 시도하거나 최대 기간을 줄이거나 속도를 줄이세요',
      Keys.less: '더 적은',
      Keys.importance: '중요성',
      Keys.chrony: '크로니',
      Keys.highRoller: '하이롤러',
      Keys.theme: '주제',
      Keys.light: '빛',
      Keys.dark: '어두운',
      Keys.auto: '자동',
      Keys.forever: '영원히',
      Keys.minSpeed: '최소 지원',
      Keys.maxDuration: '최대 기간',
      Keys.estWaitTime: '동부 표준시. 대기 시간',
      Keys.numberHint: '12 와 같은 실수를 입력하세요',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'ALGO/s',
      Keys.ALGO: 'ALGO',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: '유효하지 않은',
      Keys.join: '가입하다',
      Keys.favorites: '즐겨찾기',
      Keys.wallet: '지갑',
      Keys.blockList: '차단된 손님',
      Keys.favList: '즐겨찾기 목록',
      Keys.fav: '즐겨찾기',
      Keys.scanQr: '주사 QR',
      Keys.about: '에 대한',
      Keys.aboutPageUrl: 'https://about.2i2i.app',
      Keys.scanInWalletConnect: '사용 WalletConnect\n(e.g. Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: 'OK',
      Keys.talk: '말',
      Keys.cancel: '취소',
      Keys.ratings: '평가',
      Keys.close: '닫다',
      Keys.copyMessage: '클립보드에 복사됨',
      Keys.userBusyMessage: '사용자가 오프라인이거나 사용 중입니다..',
      Keys.logout: '로그 아웃',
      Keys.noRatingsFound: '평가를 찾을 수 없습니다',
      Keys.logoutAreYouSure: '로그아웃하시겠습니까?',
      Keys.logoutFailed: '로그아웃 실패',
      Keys.signIn: '로그인',
      Keys.signInWithEmailPassword: '이메일과 비밀번호로 로그인',
      Keys.goAnonymous: '익명으로 이동',
      Keys.or: '또는',
      Keys.signInFailed: '로그인 실패',
      Keys.somethingWantWrong: '문제가 발생했습니다',
      Keys.homePage: '홈 페이지',
      Keys.home: '찾다',
      Keys.account: '프로필',
      Keys.doneIHaveCopied: '완료 및 복사',
      Keys.profile: '주최자',
      Keys.settings: '설정',
      Keys.searchUserHint: '호스트 찾기',
      Keys.search: '찾다',
      Keys.myAccount: '내 계정',
      Keys.bidsIn: '입찰',
      Keys.bidsInPage: '페이지에서 입찰',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: '새 카드',
      Keys.createABid: '호스트 가입',
      Keys.speed: '지원하다',
      Keys.bidAmount: '입찰 금액',
      Keys.note: '참고(선택 사항)',
      Keys.bidNote: '멋진 말을 해',
      Keys.yourBioHint: '나는 #말하고 #요리하는 것을 좋아한다\n나는 가르 칠 수있다',
      Keys.yourNameHint: '내 멋진 이름',
      Keys.writeYourBio: '당신의 약력을 작성',
      Keys.writeYourName: '당신의 이름을 쓰기',
      Keys.bioExample: '예: #요리나 #농구에 대해 이야기하자',
      Keys.save: '구하다',
      Keys.required: '필수의',
      Keys.enterValidData: '유효한 데이터를 입력하세요',
      Keys.setUpAccount: '누구세요?',
      Keys.userSettings: '호스트 설정',
      Keys.userName: '사용자 이름',
      Keys.name: '사용자 이름',
      Keys.bio: '관심분야(해시태그 사용)',
      Keys.addAccount: '계정을 추가',
      Keys.walletAccount: '지갑 계정',
      Keys.walletAccountMsg: '타사 지갑을 연결하고 싶습니다.',
      Keys.recoverPassphrase: '암호로 복구',
      Keys.recoverPassPhaseMsg: '나는 25개의 비밀단어를 알고 있다',
      Keys.addLocalAccount: '로컬 계정 추가',
      Keys.addLocalAccountMsg: '이 기기에서 로컬 계정 만들기',
      Keys.swipeAndChangeAccount: '스와이프하여 계정 변경',
      Keys.insufficientBalance: '잔액 불충분',
      Keys.addBid: '가입하다',
      Keys.next: '다음',
      Keys.report: '보고서',
      Keys.block: '블록',
      Keys.unBlock: '차단 해제',
      Keys.seeMore: '더보기',
      Keys.more: '더',
      Keys.appRatingTitle: '이 회의가 마음에 드셨나요?',
      Keys.appRatingMessage: '아무 피드백?',
      Keys.appRatingSubmitButton: '제출하다',
      Keys.selectNetworkMode: '네트워크 모드 선택:',
      Keys.themeMode: '색 구성표:',
      Keys.myProfile: '내 프로필',
      Keys.bidIn: '입찰',
      Keys.bidOut: '대기 중',
      Keys.noBidFound: '입찰가를 찾을 수 없습니다.',
      Keys.noMeetingsFound: '모임을 찾을 수 없습니다',
      Keys.roomIsEmpty: '방이 비어있다',
      Keys.meetingsHistory: '회의 기록',
      Keys.history: '역사',
      Keys.friendList: '친구 목록',
      Keys.duration: '지속',
      Keys.copiedLink: '복사된 링크!',
      Keys.share: '공유하다',
      Keys.copy: '복사',
      Keys.noGuestsFound: '손님이 없습니다',
      Keys.comeAndHangOut: '이리 와서 나랑 놀아 2i2i',
      Keys.secs: '초',
      Keys.noAccountAdded: '추가된 계정 없음',
      Keys.minSupportIs: '최소 지원은',
      Keys.waitLess: '덜 기다리다',
      Keys.weAreWaiting: '우리는 기다리고 있습니다!',
      Keys.confirmInWallet: '지갑에서 확인해주세요',
      Keys.noHostsFound: '호스트를 찾을 수 없음',
      Keys.pleaseReadCarefully: '잘 읽어주세요',
      Keys.writeDownRecovery: '복구 암호(1-25단어)를 적어 두십시오. 이것이',
      Keys.recoverAccount: '향후 계정을 복구할 수 있는 유일한 방법입니다.',
      Keys.warning: '경고',
      Keys.doNotShare: '귀하의 계정에 대한 전체 액세스 권한을 부여하므로 이 단어를 누구와도 공유하지 마십시오',
      Keys.createLocalAccount: '로컬 계정 생성',
      Keys.createLocalAccountWarning:
          '귀하의 계정에 대한 전체 액세스 권한을 부여하므로 이 단어를 누구와도 공유하지 마십시오.',
      Keys.recoverAccounts: '계정 복구',
      Keys.recover: '다시 덮다',
      Keys.recoverAccountWarning: '복구하려는 계정의 유효한 키 25개를 모두 입력하십시오',
      Keys.verifyRecovery: '복구 암호 백업 확인',
      Keys.selectWord: '단어 선택',
      Keys.complete: '완벽한',
      Keys.accumulatedSupport: '누적 지원',
      Keys.startsIn: '에서 시작',
      Keys.settled: '안정된',
      Keys.waitingGuest: '손님으로 대기',
      Keys.pickUpMsg: '픽업해주세요',
      Keys.waitingFor: '기다리다',
      Keys.toPickUp: '데리러',
      Keys.Note: '메모',
      Keys.Start: '시작',
      Keys.connectingHost: '호스트를 연결하고 있습니다....',
      Keys.connectingGuest: '게스트를 연결합니다.....',
      Keys.whoTop: '누가 탑이야?',
      Keys.topSpeeds: '최고 속도',
      Keys.topDurations: '최고 기간',
      Keys.language: '앱 언어',
      Keys.inviteFriend: '프로필 링크를 팔로워와 공유하여 여기에서 만나세요',
      Keys.joinInvite: '2i2i에서 나와 함께 놀아요',
      Keys.joinOtherRoom: '일부 호스트에 가입하십시오',
      Keys.beFirstJoin: '이 호스트에 가장 먼저 가입하세요.',
      Keys.appVersion: '버전',
      Keys.logOut: '로그 아웃',
      Keys.connectAccount: '계정 연결',
      Keys.updateAvailable: '업데이트 가능',
      Keys.loginMsg: '대화로 코인을 벌다',
      Keys.loginMsg2: '2i2i\'는 게스트와 호스트가 영상통화 형태로 만날 수 있는 안전하고 프라이빗한 공간을 제공하며',
      Keys.loginMsg3: '>출시 이후 501회 회의',
      Keys.signInWithGoogle: '구글로 로그인',
      Keys.signInWithApple: 'Apple로 로그인',
      Keys.signInWithTwitter: '트위터로 로그인',
      Keys.signInAnonymously: '익명 로그인',
      Keys.searchFaq: '키워드 검색',
      Keys.noInternetTitle: '인터넷에 연결되지 않음',
      Keys.noInternetMessage: '인터넷에 연결되어 있지 않습니다. WI-FI가 켜져 있는지 확인하십시오. 비행기 모드가 꺼져 있고 다시 시도하십시오',
      Keys.loading: '로드 중...',
      Keys.noKeyFound: '이 키에서 계정을 찾을 수 없습니다',
      Keys.no: '아니요',
      Keys.yes: '예',
      Keys.transactionConfirmMsg: '지갑에서 거래를 하시겠습니까?',
      Keys.pleaseConfirm: '확인 해주세요',
      Keys.okay: '좋아요',
      Keys.connectedSocialAccount: '소셜 계정과 연결됨',
      Keys.zero: '영',
      Keys.minutes: '분',
      Keys.hours: '시간',
      Keys.days: '날',
      Keys.weeks: '주',
      Keys.months: '개월',
      Keys.years: '연령',
      Keys.thisIsYou: '이것은 당신입니다',
      Keys.deleteAccount: '계정 삭제',
      Keys.deleteAccountMessage: '2i2i에서 계정을 영구적으로 삭제하시겠습니까?',
      Keys.estMaxDuration: '최대 기간',
      Keys.waitTimeMsg: '동부 표준시. 대기 시간은',
      Keys.writeComment: '코멘트 쓰기...',
      Keys.connecting: '연결 중...',
      Keys.muted: '음소거',
      Keys.walletConnect: '지갑 연결',
      Keys.connect: '연결하다',
      Keys.receiveSendCoin: '코인을 송금/수신하려면 먼저 계정을 연결하세요.',
      Keys.cantBidUser: '이 사용자에게 입찰할 수 없습니다.',
      Keys.miniSupport: '최소 속도가 최대 지원보다 큽니다.',
      Keys.noWalletFound: '지갑 계정을 찾을 수 없습니다.',
      Keys.someOneTalk: '누군가 당신과 이야기하고 싶어합니다',
      Keys.openApp: '열려 있는',
      Keys.connectWallet: '지갑 연결',
      Keys.retry: '다시 해 보다',
      Keys.walletDesMsg1: '코인을 받으려면 계정을 연결해야 합니다. 연결을 클릭하여 지갑 앱에서 WalletConnect 계정을 연결하십시오. 그 후 2i2i로 돌아갑니다.',
      Keys.walletDesMsg2: '계정을 연결했습니다. 이제 코인을 받을 수 있습니다. 대화를 클릭하여 게스트와 연결합니다.',
      Keys.acceptBid: '입찰 수락',
      Keys.startTalk: '토크 시작',
      Keys.failToConnect: '연결에 실패했습니다. 다시 시도해 주세요.',
      Keys.cancelBid: '입찰 취소!',
      Keys.cancelBidMsg: '입찰을 취소하시겠습니까?',
    };
  }
}
