import '../../../infrastructure/commons/keys.dart';

class zh {
  Map data() {
    return {
      Keys.aboutYou: '关于你',
      Keys.aboutYouDesc: '请填写这个',
      Keys.faq: '常问问题',
      Keys.automatic: '自动的',
      Keys.shareQr: '分享自己',
      Keys.error: '错误',
      Keys.errorWhileAddBid: '添加出价时出错，请尝试其他帐户或缩短最长持续时间或降低速度',
      Keys.less: '较少的',
      Keys.importance: '重要性',
      Keys.chrony: '計時碼表',
      Keys.highRoller: '豪客賽',
      Keys.theme: '主题',
      Keys.light: '光',
      Keys.dark: '黑暗的',
      Keys.auto: '汽车',
      Keys.forever: '永远',
      Keys.minSpeed: '最小支持',
      Keys.maxDuration: '最长持续时间',
      Keys.estWaitTime: '美东时间。 等待时间是',
      Keys.numberHint: '输入实数，如 12',
      Keys.numberZeroHint: '0',
      Keys.algoPerSec: 'ALGO/s',
      Keys.ALGO: 'ALGO',
      Keys.hh: 'hh',
      Keys.mm: 'mm',
      Keys.ss: 'ss',
      Keys.invalid: '无效的',
      Keys.join: '加入',
      Keys.favorites: '收藏夹',
      Keys.wallet: '钱包',
      Keys.blockList: '被阻止的客人',
      Keys.favList: '收藏列表',
      Keys.fav: '收藏夹',
      Keys.scanQr: '扫描 QR',
      Keys.about: '关于',
      Keys.aboutPageUrl: 'https://about.2i2i.app',
      Keys.scanInWalletConnect: '利用 WalletConnect\n(例如 Algorand Wallet)',
      Keys.appName: '2i2i',
      Keys.ok: '行',
      Keys.talk: '讲话',
      Keys.cancel: '取消',
      Keys.ratings: '收视率',
      Keys.close: '关闭',
      Keys.copyMessage: '已复制到剪贴板',
      Keys.userBusyMessage: '用户离线或忙碌..',
      Keys.logout: '登出',
      Keys.noRatingsFound: '未找到评分',
      Keys.logoutAreYouSure: '您确定要退出吗？',
      Keys.logoutFailed: '注销失败',
      Keys.signIn: '登入',
      Keys.signInWithEmailPassword: '使用电子邮件和密码登录',
      Keys.goAnonymous: '匿名',
      Keys.or: '或者',
      Keys.signInFailed: '登录失败',
      Keys.somethingWantWrong: '出问题了',
      Keys.homePage: '主页',
      Keys.home: '搜索',
      Keys.account: '轮廓',
      Keys.doneIHaveCopied: '完成并复制',
      Keys.profile: '主持人',
      Keys.settings: '设置',
      Keys.searchUserHint: '寻找主机',
      Keys.search: '搜索',
      Keys.myAccount: '我的帐户',
      Keys.bidsIn: '投标',
      Keys.bidsInPage: '页面出价',
      Keys.topAppBarTitle: '2i2i',
      Keys.newCardTitle: '新卡',
      Keys.createABid: '加入主持人',
      Keys.speed: '支持',
      Keys.bidAmount: '投标金额',
      Keys.note: '备注（可选）',
      Keys.bidNote: '说点好听的',
      Keys.yourBioHint: '我喜欢#讲话和#厨师\n我能#教导',
      Keys.yourNameHint: '我酷的名字',
      Keys.writeYourBio: '写你的简历',
      Keys.writeYourName: '写你的名字',
      Keys.bioExample: '例如：让我们谈谈#烹饪 或#篮球',
      Keys.save: '保存',
      Keys.required: '必需的',
      Keys.enterValidData: '请输入有效数据',
      Keys.setUpAccount: '你是谁？',
      Keys.userSettings: '主机设置',
      Keys.userName: '用户名',
      Keys.name: '用户名',
      Keys.bio: '您的兴趣（使用主题标签）',
      Keys.addAccount: '新增帐户',
      Keys.walletAccount: '钱包账户',
      Keys.walletAccountMsg: '我想连接一个第三方钱包',
      Keys.recoverPassphrase: '使用密码恢复',
      Keys.recoverPassPhaseMsg: '我知道25个秘密词',
      Keys.addLocalAccount: '添加本地帐户',
      Keys.addLocalAccountMsg: '在此设备上创建本地帐户',
      Keys.swipeAndChangeAccount: '滑动以更改帐户',
      Keys.insufficientBalance: '余额不足',
      Keys.addBid: '加入',
      Keys.next: '下一个',
      Keys.report: '报告',
      Keys.block: '堵塞',
      Keys.unBlock: '解除封锁',
      Keys.seeMore: '查看更多',
      Keys.more: '更多的',
      Keys.appRatingTitle: '你喜欢这次会议吗？',
      Keys.appRatingMessage: '任何反馈？',
      Keys.appRatingSubmitButton: '提交',
      Keys.selectNetworkMode: '选择网络模式:',
      Keys.themeMode: '配色方案:',
      Keys.myProfile: '我的简历',
      Keys.bidIn: '投标',
      Keys.bidOut: '等待',
      Keys.noBidFound: '未找到出价',
      Keys.noMeetingsFound: '未找到会议',
      Keys.roomIsEmpty: '房間是空的',
      Keys.meetingsHistory: '会议历史',
      Keys.history: '历史',
      Keys.friendList: '好友列表',
      Keys.duration: '期间',
      Keys.copiedLink: '复制链接！',
      Keys.share: '分享',
      Keys.copy: '复制',
      Keys.noGuestsFound: '未找到客人',
      Keys.comeAndHangOut: '来和我一起出去玩 2i2i',
      Keys.secs: '秒',
      Keys.noAccountAdded: '未添加帐号',
      Keys.minSupportIs: '最小支持是',
      Keys.waitLess: '少等',
      Keys.weAreWaiting: '我们在等待！',
      Keys.confirmInWallet: '请在您的钱包中确认',
      Keys.noHostsFound: '未找到主机',
      Keys.pleaseReadCarefully: '请仔细阅读',
      Keys.writeDownRecovery: '写下您的恢复密码（1-25 个字）。 这是',
      Keys.recoverAccount: '将来恢复您的帐户的唯一方法。',
      Keys.warning: '警告',
      Keys.doNotShare: '不要与任何人分享这些词，因为它会授予对您帐户的完全访问权限',
      Keys.createLocalAccount: '创建本地帐户',
      Keys.createLocalAccountWarning: '不要与任何人分享这些词，因为它会授予对您帐户的完全访问权限.',
      Keys.recoverAccounts: '恢复账户',
      Keys.recover: '恢复',
      Keys.recoverAccountWarning: '填写您要恢复的帐户的所有 25 个有效密钥',
      Keys.verifyRecovery: '验证恢复密码备份',
      Keys.selectWord: '选择单词',
      Keys.complete: '完全的',
      Keys.accumulatedSupport: '累积支持',
      Keys.startsIn: '开始于',
      Keys.settled: '落户',
      Keys.waitingGuest: '作为客人等待',
      Keys.pickUpMsg: '请领取',
      Keys.waitingFor: '等待',
      Keys.toPickUp: '捡起',
      Keys.Note: '笔记',
      Keys.Start: 'Start',
      Keys.connectingHost: '我们正在连接主机......',
      Keys.connectingGuest: '我们正在连接客人......',
      Keys.whoTop: '谁是顶级？',
      Keys.topSpeeds: '最高速度',
      Keys.topDurations: '热门持续时间',
      Keys.language: '应用语言',
      Keys.inviteFriend: '与您的关注者分享您的个人资料链接，以便在此处与他们会面',
      Keys.joinInvite: '在 2i2i 上和我一起出去玩',
      Keys.joinOtherRoom: '请加入一些主机',
      Keys.beFirstJoin: '成为第一个加入此主持人的人',
      Keys.appVersion: '版本',
      Keys.logOut: '登出',
      Keys.connectAccount: '連接帳戶',
      Keys.updateAvailable: '更新可用',
      Keys.loginMsg: '说话赚金币',
      Keys.loginMsg2: '2i2i 以視頻通話的形式為客人和主人提供安全私密的會面空間',
      Keys.loginMsg3: '>自啟動以來的 654 次會議',
      Keys.signInWithGoogle: '用谷歌登錄',
      Keys.signInWithApple: '使用 Apple 登錄”',
      Keys.signInWithTwitter: '用 Twitter 登錄',
      Keys.signInAnonymously: '匿名登錄',
      Keys.searchFaq: '搜索关键字',
      Keys.noInternetTitle: '没有网络连接',
      Keys.noInternetMessage: '您没有连接到互联网。 确保 WI-FI 已打开。 飞行模式已关闭，然后重试',
      Keys.loading: '正在加载...',
      Keys.noKeyFound: '我们无法通过此密钥找到帐户',
      Keys.no: '不',
      Keys.yes: '是的',
      Keys.transactionConfirmMsg: '你确定用你的钱包进行交易吗？',
      Keys.pleaseConfirm: '请确认',
      Keys.okay: '好的',
      Keys.connectedSocialAccount: '与社交帐户连接',
      Keys.zero: '零',
      Keys.minutes: '分鐘',
      Keys.hours: '小時',
      Keys.days: '天',
      Keys.weeks: '週',
      Keys.months: '月',
      Keys.years: '年',
      Keys.thisIsYou: '这是你',
      Keys.deleteAccount: '删除帐户',
      Keys.deleteAccountMessage: '您确定要从 2i2i 中永久删除您的帐户吗？',
      Keys.estMaxDuration: '最长持续时间',
      Keys.waitTimeMsg: '美东时间。等待时间是',
      Keys.writeComment: '写个评论...',
      Keys.connecting: '正在连接...',
      Keys.muted: '静音',
      Keys.walletConnect: '钱包连接',
      Keys.connect: '连接',
      Keys.receiveSendCoin: '请先连接一个帐户以发送/接收硬币。',
      Keys.cantBidUser: '您不能对该用户出价',
      Keys.miniSupport: '最小速度大于最大支持',
      Keys.noWalletFound: '未找到钱包帐户。',
      Keys.someOneTalk: '有人想和你谈谈',
      Keys.openApp: '打開',
      Keys.connectWallet: '連接錢包',
      Keys.retry: '重試',
      Keys.walletDesMsg1: '要接收硬币，您需要连接一个帐户。单击连接以在您的钱包应用程序中连接 WalletConnect 帐户。之后返回 2i2i。',
      Keys.walletDesMsg2: '您已连接一个帐户。现在你可以收到硬币了。单击“交谈”以与您的访客联系。',
      Keys.acceptBid: '接受投标',
      Keys.startTalk: '开始谈话',
      Keys.failToConnect: '连接失败。请再试一次。',
      Keys.cancelBid: '取消投标！',
      Keys.cancelBidMsg: '您确定要取消出价吗？',
    };
  }
}
