import 'package:flutter/material.dart';

import '../../ui/screens/localization/app_localization.dart';

class Keys {
  static const String emailPassword = 'email-password';
  static const String anonymous = 'anonymous';
  static const String tabBar = 'tabBar';
  static const String searchTab = 'searchTabTab';
  static const String myAccountTab = 'myAccountTab';
  static const String bidsInTab = 'bidsInTab';
  static const String logout = 'logout';
  static const String alertDefault = 'alertDefault';
  static const String alertCancel = 'alertCancel';
  static const String myReadBids = 'myReadBids';
  static const String asGuest = 'As Guest';
  static const String asHost = 'As Host';
  static const String noBidFound = 'noBidFound';
  static const String noMeetingsFound = 'noMeetingsFound';
  static const String roomIsEmpty = 'roomIsEmpty';
  static const String aboutYou = 'aboutYou';
  static const String aboutYouDesc = 'aboutYouDesc';
  static const String faq = 'faq';
  static const String theme = 'theme';
  static const String light = 'LIGHT';
  static const String dark = 'DARK';
  static const String auto = 'AUTO';
  static const String estWaitTime = 'estWaitTime';
  static const String automatic = 'automatic';
  static const String shareQr = 'shareQr';
  static const String error = 'error';
  static const String errorWhileAddBid = 'errorWhileAddBid';
  static const String less = 'less';
  static const String importance = 'importance';
  static const String chrony = 'chrony';
  static const String highRoller = 'highRoller';
  static const String forever = 'forever';
  static const String ratings = 'ratings';
  static const String somethingWantWrong = 'somethingWantWrong';
  static const String minSpeed = 'minSpeed';
  static const String maxDuration = 'maxDuration';
  static const String numberHint = 'numberHint';
  static const String numberZeroHint = 'numberZeroHint';
  static const String noRatingsFound = 'noRatingsFound';
  static const String noRedeemCoinsFound = 'noRedeemCoinsFound';
  static const String algoPerSec = 'algoPerSec';
  static const String algoPerHr = 'algoPerHr';
  static const String hh = 'hh';
  static const String mm = 'mm';
  static const String ss = 'ss';
  static const String invalid = 'invalid';
  static const String join = 'join';
  static const String favorites = 'favorites';
  static const String wallet = 'wallet';
  static const String redeemCoin = 'redeemCoin';
  static const String blockList = 'blockList';
  static const String favList = 'favList';
  static const String fav = 'fav';
  static const String scanQr = 'scanQr';
  static const String about = 'about';
  static const String aboutPageUrl = 'aboutPageUrl';
  static const String scanInWalletConnect = 'scanInWalletConnect';
  static const String appName = 'appName';
  static const String ok = 'ok';
  static const String talk = 'talk';
  static const String cancel = 'cancel';
  static const String close = 'close';
  static const String copyMessage = 'copyMessage';
  static const String userBusyMessage = 'userBusyMessage';
  static const String logoutAreYouSure = 'logoutAreYouSure';
  static const String logoutFailed = 'logoutFailed';
  static const String signIn = 'signIn';
  static const String signInWithEmailPassword = 'signInWithEmailPassword';
  static const String goAnonymous = 'goAnonymous';
  static const String or = 'or';
  static const String signInFailed = 'signInFailed';
  static const String homePage = 'homePage';
  static const String home = 'home';
  static const String account = 'account';
  static const String doneIHaveCopied = 'doneIHaveCopied';
  static const String profile = 'profile';
  static const String settings = 'settings';
  static const String searchUserHint = 'searchUserHint';
  static const String search = 'search';
  static const String myAccount = 'myAccount';
  static const String bidsIn = 'bidsIn';
  static const String bidsInPage = 'bidsInPage';
  static const String topAppBarTitle = 'topAppBarTitle';
  static const String newCardTitle = 'newCardTitle';
  static const String createABid = 'createABid';
  static const String speed = 'speed';
  static const String bidAmount = 'bidAmount';
  static const String duration = 'duration';
  static const String note = 'note';
  static const String bidNote = 'bidNote';
  static const String yourBioHint = 'yourBioHint';
  static const String yourNameHint = 'yourNameHint';
  static const String writeYourBio = 'writeYourBio';
  static const String writeYourName = 'writeYourName';
  static const String bioExample = 'bioExample';
  static const String save = 'save';
  static const String required = 'required';
  static const String enterValidData = 'enterValidData';
  static const String setUpAccount = 'setUpAccount';
  static const String userSettings = 'userSettings';
  static const String userName = 'userName';
  static const String name = 'name';
  static const String bio = 'bio';
  static const String addAccount = 'addAccount';
  static const String walletAccount = 'walletAccount';
  static const String walletAccountMsg = 'walletAccountMsg';
  static const String recoverPassphrase = 'recoverPassphrase';
  static const String recoverPassPhaseMsg = 'recoverPassPhaseMsg';
  static const String estMaxDuration = 'estMaxDuration';
  static const String swipeAndChangeAccount = 'swipeAndChangeAccount';
  static const String insufficientBalance = 'insufficientBalance';
  static const String addBid = 'addBid';
  static const String next = 'copyAndNext';
  static const String report = 'report';
  static const String block = 'block';
  static const String unBlock = 'unBlock';
  static const String seeMore = 'seeMore';
  static const String appRatingTitle = 'appRatingTitle';
  static const String appRatingMessage = 'appRatingMessage';
  static const String appRatingSubmitButton = 'appRatingSubmitButton';
  static const String selectNetworkMode = 'selectNetworkMode';
  static const String themeMode = 'themeMode';
  static const String myProfile = 'myProfile';
  static const String bidIn = 'bidIn';
  static const String bidOut = 'bidOut';
  static const String meetingsHistory = 'meetingsHistory';
  static const String share = 'share';
  static const String copy = 'copy';
  static const String comeAndHangOut = 'Come and hang out with me on 2i2i';
  static const String history = 'history';
  static const String friendList = 'friendList';
  static const String copiedLink = 'copiedLink';
  static const String more = 'more';
  static const String noGuestsFound = 'noGuestsFound';
  static const String secs = 'secs';
  static const String noAccountAdded = 'noAccountAdded';
  static const String minSupportIs = 'minSupportIs';
  static const String waitLess = 'waitLess';
  static const String weAreWaiting = 'weAreWaiting';
  static const String confirmInWallet = 'confirmInWallet';
  static const String noHostsFound = 'noHostsFound';
  static const String ALGO = 'ALGO';
  static const String pleaseReadCarefully = 'pleaseReadCarefully';
  static const String writeDownRecovery = 'writeDownRecovery';
  static const String warning = 'warning';
  static const String doNotShare = 'doNotShare';
  static const String selectWord = 'selectWord';
  static const String complete = 'complete';
  static const String accumulatedSupport = 'accumulatedSupport';
  static const String startsIn = 'startsIn';
  static const String settled = 'settled';
  static const String waitingGuest = 'waitingGuest';
  static const String pickUpMsg = 'pickUpMsg';
  static const String waitingFor = 'waitingFor';

  static const String toPickUp = 'toPickUp';
  static const String Note = 'Note';
  static const String Start = 'Start';
  static const String connectingHost = 'connectingHost';
  static const String connectingGuest = 'connectingGuest';
  static const String whoTop = 'whoTop';
  static const String topValues = 'topValues';
  static const String topSpeeds = 'topSpeeds';
  static const String topDurations = 'topDurations';
  static const String language = 'Language';
  static const String inviteFriend = 'inviteFriend';
  static const String joinInvite = 'joinInvite';
  static const String joinOtherRoom = 'joinOtherRoom';
  static const String beFirstJoin = 'beFirstJoin';
  static const String appVersion = 'appVersion';
  static const String logOut = 'logOut';

  static const String connectAccount = 'connectAccount';
  static const String updateAvailable = 'updateAvailable';
  static const String loginMsg = 'loginMsg';
  static const String loginMsg2 = 'loginMsg2';
  static const String loginMsg3 = 'loginMsg3';
  static const String signInWithGoogle = 'signInWithGoogle';
  static const String signInWithApple = 'signInWithApple';
  static const String signInWithTwitter = 'signInWithTwitter';
  static const String signInAnonymously = 'signInAnonymously';
  static const String signInWithWalletConnect = 'Wallet Connect';

  static const String searchFaq = 'searchFaq';
  static const String noInternetTitle = 'noInternetTitle';
  static const String noInternetMessage = 'noInternetMessage';
  static const String loading = 'loading';
  static const String noKeyFound = 'noKeyFound';
  static const String no = 'no';
  static const String yes = 'Yes';
  static const String transactionConfirmMsg = 'Are you sure to do the transaction from your wallet?';
  static const String pleaseConfirm = 'Please Confirm';
  static const String okay = 'Okay';

  static const String connectedSocialAccount = 'connectedSocialAccount';

  static const String zero = 'zero';
  static const String minutes = 'minutes';
  static const String hours = 'hours';
  static const String days = 'days';
  static const String weeks = 'weeks';
  static const String months = 'months';
  static const String years = 'years';

  static const String thisIsYou = 'thisIsYou';

  static const String deleteAccount = 'deleteAccount';
  static const String deleteAccountMessage = 'deleteAccountMessage';
  static const String waitTimeMsg = 'waitTimeMsg';
  static const String writeComment = 'writeComment';
  static const String connecting = 'connecting';
  static const String muted = 'muted';
  static const String walletConnect = 'Wallet Connect';
  static const String connect = 'Connect';
  static const String receiveSendCoin = 'Please first connect an account to send/receive energy.';
  static const String cantBidUser = 'You can not bid to this user';
  static const String miniSupport = 'Minimum speed is greater then Maximum Support';
  static const String noWalletFound = 'No wallet account found.';
  static const String someOneTalk = 'Someone wants to talk with you';

  static const String openApp = 'Open';

  static const String connectWallet = 'Connect Wallet';

  static const String retry = 'Retry';

  static const String signInWithInstagram = 'Sign in with Instagram';

  static const String walletDesMsg1 =
      'To receive energy, you need to connect an account. Click on Connect to to connect a WalletConnect account in your wallet app. Afterwards return to 2i2i.';
  static const String walletDesMsg2 = 'You have connected an account. Now you can receive energy. Click Talk to connect with your Guest.';

  static const String acceptBid = 'Accept Bid';
  static const String startTalk = 'Start to Talk';
  static const String failToConnect = 'Failed to connect. Please try again.';

  static const String cancelBid = 'Cancel Bid!';
  static const String cancelBidMsg = 'Are you sure want to cancel bid?';
}

extension CustomTranslation on String {
  String tr(BuildContext context) {
    return ApplicationLocalizations.of(context)?.translate(this) ?? '';
  }
}
