// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8E8sAtlaDZveourRnfJcQkpJCF3pPcc',
    appId: '1:347734179578:web:f9c11616c64e12c643d343',
    messagingSenderId: '347734179578',
    projectId: 'app-2i2i',
    authDomain: 'app-2i2i.firebaseapp.com',
    storageBucket: 'app-2i2i.appspot.com',
    measurementId: 'G-BXKG3DRTJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb3Bd0me1N5-aMqoR4Y-ALbq9oA3h8p7A',
    appId: '1:347734179578:android:221a08f307315a3543d343',
    messagingSenderId: '347734179578',
    projectId: 'app-2i2i',
    storageBucket: 'app-2i2i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoweDY_bjF863GDHJzdTjIQlq24Nss0I',
    appId: '1:347734179578:ios:db00c46f507b723043d343',
    messagingSenderId: '347734179578',
    projectId: 'app-2i2i',
    storageBucket: 'app-2i2i.appspot.com',
    androidClientId: '347734179578-pack539ulqgoo7nbhhi4k2gnnr3s1qjg.apps.googleusercontent.com',
    iosClientId: '347734179578-q66t59heeh98emoiaqrhhsn61lurbvsj.apps.googleusercontent.com',
    iosBundleId: 'app.2i2i',
  );
}
